# Generated by Django 4.2.3 on 2023-07-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL('CREATE SCHEMA IF NOT EXISTS warehouse;'),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.TextField(choices=[('Создан', 'Создан'), ('Готов к отгрузке', 'Готов к отгрузке')], verbose_name='Статус')),
                ('warehouse', models.TextField(choices=[('Склад_1', 'Склад_1'), ('Склад_2', 'Склад_2')], verbose_name='Склад')),
                ('creation_dt', models.DateTimeField(verbose_name='Дата и время создания')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'warehouse"."order',
            },
        ),
    ]
